services:
  backend:
    build :
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP_ENV=dev
      - DSN=${DSN}
      - SECRET=${SECRET}
      - API_KEY=${API_KEY}
      - PARSER_URL=${PARSER_URL}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mongo
    volumes:
      - db-data:/data/db
      - ./docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: recruitment
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'"]
      interval: 4s
      timeout: 2s
      retries: 5
  
volumes:
  db-data:
