services:
  backend:
    context: .
    port:
      - 3000:3000
    environment:
      - HOST=db
      - DB_PORT=5432
      - USER_NAME=postgres
      - DB_NAME=recruitment
      - PASSWORD=postgres
      - SECRET=secret
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/seed/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=recruitment
      - POSTGRES_PASSWORD=postgres
    port:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      timeout: 2s
      retries: 5
  
volumes:
  db-data: